name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Action
        id: test
        uses: ./
        with:
          tag: 'latest'
          base-image-urls: |
            hello-world
            alpine
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this Release
            - Resolve Docker Images Action ${{ github.ref }}
            
            ## Usage
            ```yaml
            - name: Resolve Docker Images
              uses: optivem/resolve-docker-images-action@${{ github.ref }}
              with:
                tag: 'v1.0.0'
                base-image-urls: |
                  myregistry.azurecr.io/myapp/api
                  myregistry.azurecr.io/myapp/web
            ```
          draft: false
          prerelease: false